-- Base de dato utilizado y actualizar tabla creada
USE Planeamiento
DROP TABLE #PRUEBA
DROP TABLE #test
DROP TABLE #recep_tmp
DROP TABLE RECEP_TABLA
GO
-- IMPORTAR DATA DE RECECPCION
SELECT * INTO #recep_tmp
FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0',
		'Excel 12.0;Database=D:\Documentos Personales\Documents\Planeamiento\Scripts_Planeamiento\Reporte_AOC_RECEP\Analisis_Recepcion\Doc_Origen\recepc__01082019_09032020.xlsx;HDR=YES', 
		'SELECT * FROM [recepc__01082019_09032020$]')
GO

-- Primeras condiciones para crear el analisis de recepcion
SELECT recep.ORDEN_COMPRA AS ORDEN_COMPRA,
	   recep.ELEMENTO AS ELEMENTO,
	   recep.CODIGO_BIEN AS CODIGO_BIEN, 
	   recep.DESCRIPCION AS DESCRIPCION, 
	   recep.UNIDAD_DE_MEDIDA AS UNIDAD_DE_MEDIDA,
	   RIGHT(recep.UBICN_PRINCIPAL, IIF(CAST(LEN(recep.UBICN_PRINCIPAL) AS int)=0,0,CAST(LEN(recep.UBICN_PRINCIPAL) AS int)-4)) AS FONDO,
	   CAST(SUM(recep.CANT_RECIBIDO)AS float) AS CANT_RECIBIDO,
	   recep.RECEPCION_COMPLETADA

INTO #PRUEBA
FROM #recep_tmp AS recep 
GROUP BY recep.ORDEN_COMPRA, recep.UBICN_PRINCIPAL, recep.ELEMENTO, recep.CODIGO_BIEN,recep.DESCRIPCION,recep.UNIDAD_DE_MEDIDA,recep.RECEPCION_COMPLETADA
ORDER BY recep.ORDEN_COMPRA, recep.ELEMENTO
GO

DELETE FROM #PRUEBA WHERE CANT_RECIBIDO = 0
GO

SELECT recep.ORDEN_COMPRA AS ORDEN_COMPRA, recep.ELEMENTO AS ELEMENTO,
	   recep.CODIGO_BIEN AS CODIGO_BIEN,
	   SUM(IIF(recep.RECEPCION_COMPLETADA = 'Y',recep.CANT_RECIBIDO,0)) AS CANT_RECIBIDA -- SUMA TODOS LOS N e Y
INTO #test
FROM #PRUEBA AS recep --WHERE recep.CODIGO_BIEN = '16180003' AND recep.ORDEN_COMPRA = 'P0219367'
GROUP BY recep.ORDEN_COMPRA, recep.CODIGO_BIEN, recep.ELEMENTO--,recep.RECEPCION_COMPLETADA--,recep.CANT_RECIBIDO
GO

--SELECT * FROM #test WHERE ORDEN_COMPRA = 'P0213468' AND CODIGO_BIEN = '91020156'

SELECT recep.ORDEN_COMPRA AS ORDEN_COMPRA,
	   recep.FONDO,
	   recep.ELEMENTO AS ELEMENTO,
	   recep.CODIGO_BIEN AS CODIGO_BIEN, 
	   recep.DESCRIPCION AS DESCRIPCION, 
	   recep.UNIDAD_DE_MEDIDA AS UNIDAD_DE_MEDIDA,
	   CAST(SUM(recep.CANT_RECIBIDO)AS float) AS CANT_ENTREGADA,
	   test.CANT_RECIBIDA AS CANT_RECIBIDA

INTO RECEP_TABLA
FROM #PRUEBA AS recep 
LEFT JOIN #test AS test ON test.ORDEN_COMPRA = recep.ORDEN_COMPRA AND test.CODIGO_BIEN = recep.CODIGO_BIEN AND test.ELEMENTO = recep.ELEMENTO
WHERE recep.CANT_RECIBIDO > 0
GROUP BY recep.ORDEN_COMPRA, recep.FONDO, recep.ELEMENTO, recep.CODIGO_BIEN,recep.DESCRIPCION,recep.UNIDAD_DE_MEDIDA,test.CANT_RECIBIDA, test.ELEMENTO--,recep.RECEPCION_COMPLETADA,
ORDER BY recep.ORDEN_COMPRA, recep.ELEMENTO
GO

--SELECT * FROM RECEP_TABLA WHERE ORDEN_COMPRA = 'P0217358' AND CODIGO_BIEN = '76220016'
--ORDER BY ELEMENTO


